[project]
name = "configur8"
version = "1.6.1"
description = "Type-safe configuration and validation library"
authors = [{ name = "Nick Joyce", email = "nick@stratuscode.com" }]
requires-python = ">=3.7,<4.0"
readme = "README.md"
license = { text = "MIT" }

dependencies = [
    "email-validator>=1.3.1",
    "typing-extensions>=4.0.0",
]

[tool.pdm.dev-dependencies]
dev = [
    "codecov",
    "flake8",
    "mypy",
    "pytest-cov",
    "pytest-mock",
    "pytest-mypy-plugins",
    "pytest",
    "types-pyyaml",
    "setuptools>=67.2.0",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
