[tool.poetry]
name = "configur8"
version = "0.1.0"
description = "Python configuration and validation library"
authors = ["Nick Joyce <nick@stratuscode.com>"]

[tool.poetry.dependencies]
python = "^3.8"
email-validator = ">= 1.1.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.2"
pytest-mypy-plugins = "^1.9.3"
mypy = "^0.961"
flake8 = "^4.0.1"
codecov = "^2.1.12"
twine = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
