version: "3"

vars:
  # format must be MAJOR.MINOR
  PYTHON_VERSION: 3.8
  GIT_COMMIT:
    sh: git rev-parse --short HEAD
  # whether the git working directory is clean
  GIT_TREE_STATE:
    sh: |
      if [[ $(git status --porcelain=v1 2>/dev/null | wc -l | xargs) = "0" ]]; then
        echo "clean"
      else
        echo "dirty"
      fi

includes:
  pdm:
    taskfile: .taskfiles/pdm.yml
    vars:
      PYTHON_VERSION: '{{.PYTHON_VERSION}}'

tasks:
  package:
    desc: Build Python package, ready for publishing to PyPI.
    sources:
      - src/**/*
    cmds:
      - task: pdm:build

  publish:
    desc: Publish Python package to PyPI.
    deps:
      - package
    cmds:
      - task: pdm:publish

  test:
    cmds:
      - task: pdm:run
        vars:
          ARGS: >-
            pytest
            --cov-report html --cov-report term --cov=.
            --mypy-ini-file=./mypy.ini
            {{.CLI_ARGS}}

  lint:
    cmds:
      - task: pdm:run
        vars:
          ARGS: mypy src
      - task: pdm:run
        vars:
          ARGS: flake8 src
