version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: package
          filters:
            tags:
              only: /.*/
      - publish:
          context: publish
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - setup
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test lint
            codecov

  publish:
    docker:
      - image: circleci/python:3.8
    steps:
      - setup
      - run:
          name: create packages
          command: |
            . venv/bin/activate
            make package
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            make publish

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "setup.cfg" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools wheel
            make dev
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "setup.cfg" }}
          paths:
            - "venv"
            - "/home/circleci/.cache/pip"
