name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          version: 1.4.0
          enable-pep582: true
      - name: Set up Task
        uses: arduino/setup-task@v1
      - name: Configure credentials
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: >-
          pdm config repository.pypi.username "__token__"
          pdm config repository.pypi.password "${PYPI_TOKEN}"
      - name: Install Python dependencies
        run: task pdm:install PYTHON_VERSION=${{ matrix.python-version }}
      - name: Build package
        run: task package PYTHON_VERSION=${{ matrix.python-version }}
      - name: Publish package
        run: task publish PYTHON_VERSION=${{ matrix.python-version }}
